swagger: '2.0'
info:
  x-ibm-name: simple-api-01
  title: Simple API 01
  version: 0.4.6
  description: 'Consume el API: https://apicsimpleapi01.mybluemix.net/rest/objetos/'
  contact:
    name: aalva
    email: aalva@gapsi.com.mx
    url: 'http://grupoasesores.com.mx/'
  termsOfService: Es un API de prueba
  license:
    name: GAPSI 1.0
    url: 'http://grupoasesores.com.mx/'
schemes:
  - https
host: $(catalog.host)
basePath: /api
consumes:
  - application/json
produces:
  - application/json
securityDefinitions: {}
x-ibm-configuration:
  testable: true
  enforced: true
  cors:
    enabled: true
  catalogs:
    apic-dev:
      properties:
        runtime-url: $(TARGET_URL)
    sb:
      properties:
        runtime-url: 'https://apicsimpleapi01.mybluemix.net'
        invoke-tls-profile: 'client:Loopback-client'
  assembly:
    execute:
      - activity-log:
          title: activity-log
          content: payload
          error-content: payload
          version: 1.0.0
      - operation-switch:
          title: operation-switch
          case:
            - operations:
                - listarObjetos01
              execute:
                - invoke:
                    target-url: 'http://simplerest.mybluemix.net/rest/objetos/'
                    tls-profile: $(invoke-tls-profile)
                    verb: GET
                    title: Listar
            - operations:
                - crearObjeto01
              execute:
                - invoke:
                    title: Crear
                    timeout: 60
                    verb: POST
                    cache-response: protocol
                    cache-ttl: 900
                    stop-on-error:
                      - null
                    version: 1.0.0
                    target-url: 'http://simplerest.mybluemix.net/rest/objetos/objeto01'
            - operations:
                - consultarObjeto01
              execute:
                - invoke:
                    title: Consultar
                    timeout: 60
                    verb: GET
                    cache-response: protocol
                    cache-ttl: 900
                    stop-on-error:
                      - null
                    version: 1.0.0
                    target-url: 'http://simplerest.mybluemix.net/rest/objetos/objeto01/{id}'
            - operations:
                - eliminarObjeto01
              execute:
                - invoke:
                    title: Eliminar
                    timeout: 60
                    verb: DELETE
                    cache-response: protocol
                    cache-ttl: 900
                    stop-on-error:
                      - null
                    version: 1.0.0
                    target-url: 'http://simplerest.mybluemix.net/rest/objetos/objeto01/{id}'
          otherwise: []
          version: 1.0.0
      - activity-log:
          title: activity-log
          content: payload
          error-content: payload
          version: 1.0.0
  gateway: datapower-gateway
  properties:
    runtime-url:
      value: ''
      description: ''
      encoded: false
    invoke-tls-profile:
      value: ''
      description: ''
      encoded: false
paths:
  /objetos/:
    get:
      responses:
        '200':
          description: 200 OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Objeto01'
        '204':
          description: No Content
      tags:
        - consultar
        - obtener
        - listar
      summary: Devuelve la lista de Objetos01
      operationId: listarObjetos01
  /objetos/objeto01:
    post:
      responses:
        '200':
          description: 200 OK
          schema:
            $ref: '#/definitions/Objeto01'
      tags:
        - crear
        - nuevo
      operationId: crearObjeto01
      description: Crea un Objeto01
      parameters:
        - name: objeto01
          required: true
          in: body
          schema:
            $ref: '#/definitions/Objeto01'
          description: Datos del objeto01 a crear
      summary: Crea un Objeto01 con los datos proporcionados
  '/objetos/objeto01/{id}':
    get:
      responses:
        '200':
          description: 200 OK
          schema:
            $ref: '#/definitions/Objeto01'
        '204':
          description: 204 No content
          schema:
            $ref: '#/definitions/Objeto01'
      tags:
        - consulta
      summary: Obtiene el Objeto01 al que pertenece el id
      operationId: consultarObjeto01
      parameters:
        - name: id
          type: string
          required: true
          in: path
    delete:
      responses:
        '200':
          description: 200 OK
          schema:
            $ref: '#/definitions/Objeto01'
        '204':
          description: 204 No content
          schema:
            $ref: '#/definitions/Objeto01'
      tags:
        - eliminar
        - borrar
      summary: Elimina al Objeto01 al que corresponde el id
      operationId: eliminarObjeto01
      parameters:
        - name: id
          type: string
          required: true
          in: path
          description: Id del Objeto01 a eliminar
definitions:
  Objeto01:
    properties:
      id:
        type: string
        format: uuid
        example: d290f1ee-6c54-4b01-90e6-d701748f0851
      propiedadString:
        properties: {}
        type: string
        example: abcde
      propiedadInt:
        properties: {}
        type: string
        format: int32
        example: '12345'
      subObjeto01:
        properties: {}
        $ref: '#/definitions/SubObjeto01'
    additionalProperties: true
  SubObjeto01:
    properties:
      propiedadString:
        type: string
        example: xyz
    additionalProperties: true
externalDocs:
  url: 'http://grupoasesores.com.mx/'
  description: 'No hay documentación :D'
